FROM node:12
COPY . /src

ARG NPM_TOKEN
ENV NPM_TOKEN="${NPM_TOKEN}"

RUN cd /src && npm install

ARG PORT=3000
ENV PORT="${PORT}"

ARG UNIFORM_API_URL
ENV UNIFORM_API_URL="${UNIFORM_API_URL}"

ARG UNIFORM_API_TOKEN
ENV UNIFORM_API_TOKEN="${UNIFORM_API_TOKEN}"

ARG AZURE_STORAGE_ACCOUNT
ENV AZURE_STORAGE_ACCOUNT="${AZURE_STORAGE_ACCOUNT}"

ARG AZURE_STORAGE_ACCESS_KEY
ENV AZURE_STORAGE_ACCESS_KEY="${AZURE_STORAGE_ACCESS_KEY}"

# redirect output because Azure DevOps can't handle some chars from it
RUN cd /src && npm run build > build.log

EXPOSE ${PORT}

HEALTHCHECK --interval=5s \
            --timeout=5s \
            --retries=6 \
            CMD curl -fs "http://localhost:${PORT}/-/uniform/status?token=${UNIFORM_API_TOKEN}" || exit 1

CMD [ "node", "/src/server.js" ]
